schema: "classroom50/repo-config/v1"
classroom: "ds212"
assignment: "portfolio"
owner:
  username: "ebyanh"
  id: 269963365
  accepted_at: "2026-09-12T04:04:15Z"
source:
  owner: "mac-ds212-f26"
  owner_id: 323652586
  repo: "portfolio-template"
  branch: "main"
